base_url = "https://ericscouten.me"

title = "Eric Scouten :: Me"
description = "A few personal notes and opinions."
default_language = "en"

theme = "zola-es-theme"

compile_sass = true
build_search_index = true

generate_feed = true
feed_filename = "rss.xml"

[markdown]
highlight_code = false
smart_punctuation = true

[extra]
endmark = true
es_site = "me"
